import { SkillKey } from "../actor/actor.interface";
import { EquipmentRule } from "./item.interface";

export enum SpellType {
  Cantrip = "cantrip",
  Basic = "basic",
  Greater = "greater",
}

export enum EquipmentType {
  Consumable = "consumable",
  Equipment = "equipment",
  Outfit = "outfit",
  Weapon = "weapon",
}

export enum TrademarkItemType {
  Outfit = "outfit",
  Weapon = "weapon",
}

export const SpellTypes: Record<SpellType, string> = {
  [SpellType.Cantrip]: "CRYPTOMANCER.SpellType.cantrip",
  [SpellType.Basic]: "CRYPTOMANCER.SpellType.basic",
  [SpellType.Greater]: "CRYPTOMANCER.SpellType.greater",
};

export const EquipmentTypes: Record<EquipmentType, string> = {
  [EquipmentType.Consumable]: "CRYPTOMANCER.EquipmentType.consumable",
  [EquipmentType.Equipment]: "CRYPTOMANCER.EquipmentType.equipment",
  [EquipmentType.Outfit]: "CRYPTOMANCER.EquipmentType.outfit",
  [EquipmentType.Weapon]: "CRYPTOMANCER.EquipmentType.weapon",
};

export const OutfitRules: Record<string, EquipmentRule> = {
  alchemicalArmor: {
    key: "alchemicalArmor",
    label: "EquipmentRules.alchemicalArmor",
    custom: false,
    compendium: "outfit-rules",
    journal: "GZetsxBM31aIPKMP",
  },
  damageReduction: {
    key: "damageReduction",
    label: "EquipmentRules.damageReduction",
    custom: false,
    compendium: "outfit-rules",
    journal: "nTaOnuWJDu1Bnsrg",
    value: 0,
  },
  distracting: {
    key: "distracting",
    label: "EquipmentRules.distracting",
    custom: false,
    compendium: "outfit-rules",
    journal: "KTlwNqk22ZQ9boK5",
  },
  heavy: {
    key: "heavy",
    label: "EquipmentRules.heavy",
    custom: false,
    compendium: "outfit-rules",
    journal: "SpzoIovwFAZtsdtL",
  },
  innocuous: {
    key: "innocuous",
    label: "EquipmentRules.innocuous",
    custom: false,
    compendium: "outfit-rules",
    journal: "G7VQ3b3wtONDVtcG",
  },
  natural: {
    key: "natural",
    label: "EquipmentRules.natural",
    custom: false,
  },
  restricting: {
    key: "restricting",
    label: "EquipmentRules.restricting",
    custom: false,
    compendium: "outfit-rules",
    journal: "kJ6qJugS2COwo8OO",
  },
  smugglersLining: {
    key: "smugglersLining",
    label: "EquipmentRules.smugglersLining",
    custom: false,
    compendium: "outfit-rules",
    journal: "p8518z1XzQ3TH0IK",
  },
  stationSignifierFellowTraveller: {
    key: "stationSignifierFellowTraveller",
    label: "EquipmentRules.stationSignifierFellowTraveller",
    custom: false,
    compendium: "outfit-rules",
    journal: "hf6c77gAadUsw87R",
  },
  stationSignifierHighborn: {
    key: "stationSignifierHighborn",
    label: "EquipmentRules.stationSignifierHighborn",
    custom: false,
    compendium: "outfit-rules",
    journal: "hf6c77gAadUsw87R",
  },
  stationSignifierOutlander: {
    key: "stationSignifierOutlander",
    label: "EquipmentRules.stationSignifierOutlander",
    custom: false,
    compendium: "outfit-rules",
    journal: "hf6c77gAadUsw87R",
  },
  stationSignifierVeteran: {
    key: "stationSignifierVeteran",
    label: "EquipmentRules.stationSignifierVeteran",
    custom: false,
    compendium: "outfit-rules",
    journal: "hf6c77gAadUsw87R",
  },
};

export const WeaponRules: Record<string, EquipmentRule> = {
  attachment: {
    key: "attachment",
    label: "EquipmentRules.attachment",
    custom: false,
    compendium: "weapon-rules",
    journal: "upX5Ca7gjy01JrWD",
  },
  balanced: {
    key: "balanced",
    label: "EquipmentRules.balanced",
    custom: false,
    compendium: "weapon-rules",
    journal: "vnaHtxAtLihrskWw",
  },
  bruteMelee: {
    key: "bruteMelee",
    label: "EquipmentRules.bruteMelee",
    custom: false,
    skill: "bruteMelee",
    compendium: "weapon-rules",
    journal: "2pJTrWGhCzG81STZ",
  },
  concealable: {
    key: "concealable",
    label: "EquipmentRules.concealable",
    custom: false,
    compendium: "weapon-rules",
    journal: "6q3u5VM8O3E3St0s",
  },
  cumbersome: {
    key: "cumbersome",
    label: "EquipmentRules.cumbersome",
    custom: false,
    compendium: "weapon-rules",
    journal: "OuN9jf23IExoQnQx",
  },
  damage: {
    key: "damage",
    label: "EquipmentRules.damage",
    custom: false,
    compendium: "weapon-rules",
    journal: "B1ggF5qYc4N61qcW",
    value: 0,
  },
  dirty: {
    key: "dirty",
    label: "EquipmentRules.dirty",
    custom: false,
    compendium: "weapon-rules",
    journal: "beRJLbpel8t6eBn4",
  },
  firedMissile: {
    key: "firedMissile",
    label: "EquipmentRules.firedMissile",
    custom: false,
    skill: "firedMissile",
    compendium: "weapon-rules",
    journal: "5WHCGtOCMv193KLx",
  },
  kinetic: {
    key: "kinetic",
    label: "EquipmentRules.kinetic",
    custom: false,
    compendium: "weapon-rules",
    journal: "VgToqFrVe7ejpMaj",
  },
  light: {
    key: "light",
    label: "EquipmentRules.light",
    custom: false,
    compendium: "weapon-rules",
    journal: "DR86nbOXftnDJfkG",
  },
  loud: {
    key: "loud",
    label: "EquipmentRules.loud",
    custom: false,
    compendium: "weapon-rules",
    journal: "X4FG6oIqdeT3mxq5",
  },
  overwhelming: {
    key: "overwhelming",
    label: "EquipmentRules.overwhelming",
    custom: false,
    compendium: "weapon-rules",
    journal: "9CNeinBTXn6LYaCi",
  },
  preciseMelee: {
    key: "preciseMelee",
    label: "EquipmentRules.preciseMelee",
    custom: false,
    skill: "preciseMelee",
    compendium: "weapon-rules",
    journal: "7lkCweZ1AFTg6I94",
  },
  ranged: {
    key: "ranged",
    label: "EquipmentRules.ranged",
    custom: false,
    compendium: "weapon-rules",
    journal: "4yQufqjaubpkzkoo",
  },
  short: {
    key: "short",
    label: "EquipmentRules.short",
    custom: false,
    compendium: "weapon-rules",
    journal: "cxrgaPvrhxnbOncH",
  },
  slowReload: {
    key: "slowReload",
    label: "EquipmentRules.slowReload",
    custom: false,
    compendium: "weapon-rules",
    journal: "t9qYr5Xvc0zWOvLd",
    value: 0,
  },
  spread: {
    key: "spread",
    label: "EquipmentRules.spread",
    custom: false,
    compendium: "weapon-rules",
    journal: "6JfGjAqIXbxEkfMF",
  },
  stuntedRange: {
    key: "stuntedRange",
    label: "EquipmentRules.stuntedRange",
    custom: false,
    compendium: "weapon-rules",
    journal: "ceXXjoDTWW6REmSL",
  },
  thrownMissile: {
    key: "thrownMissile",
    label: "EquipmentRules.thrownMissile",
    custom: false,
    skill: "thrownMissile",
    compendium: "weapon-rules",
    journal: "aOkX01lemXNa8sYS",
  },
  twoHanded: {
    key: "twoHanded",
    label: "EquipmentRules.twoHanded",
    custom: false,
    compendium: "weapon-rules",
    journal: "DDx0glzdA1p2dPxz",
  },
  unarmedMelee: {
    key: "unarmedMelee",
    label: "EquipmentRules.unarmedMelee",
    custom: false,
    skill: "unarmedMelee",
    compendium: "weapon-rules",
    journal: "kzHQncqDG0RSsedf",
  },
};

export const SkillRules: Record<SkillKey, EquipmentRule> = {
  acrobatics: {
    key: "acrobatics",
    label: "Skill.acrobatics",
    custom: false,
    skill: "acrobatics",
  },
  alchemy: {
    key: "alchemy",
    label: "Skill.alchemy",
    custom: false,
    skill: "alchemy",
  },
  athletics: {
    key: "athletics",
    label: "Skill.athletics",
    custom: false,
    skill: "athletics",
  },
  beastKen: {
    key: "beastKen",
    label: "Skill.beastKen",
    custom: false,
    skill: "beastKen",
  },
  bruteMelee: {
    key: "bruteMelee",
    label: "Skill.bruteMelee",
    custom: false,
    skill: "bruteMelee",
    compendium: "weapon-rules",
    journal: "2pJTrWGhCzG81STZ",
  },
  charm: {
    key: "charm",
    label: "Skill.charm",
    custom: false,
    skill: "charm",
  },
  craft: {
    key: "craft",
    label: "Skill.craft",
    custom: false,
    skill: "craft",
  },
  deception: {
    key: "deception",
    label: "Skill.deception",
    custom: false,
    skill: "deception",
  },
  escapeArtistry: {
    key: "escapeArtistry",
    label: "Skill.escapeArtistry",
    custom: false,
    skill: "escapeArtistry",
  },
  featOfStrength: {
    key: "featOfStrength",
    label: "Skill.featOfStrength",
    custom: false,
    skill: "featOfStrength",
  },
  firedMissile: {
    key: "firedMissile",
    label: "Skill.firedMissile",
    custom: false,
    skill: "firedMissile",
    compendium: "weapon-rules",
    journal: "5WHCGtOCMv193KLx",
  },
  lockPicking: {
    key: "lockPicking",
    label: "Skill.lockPicking",
    custom: false,
    skill: "lockPicking",
  },
  medicine: {
    key: "medicine",
    label: "Skill.medicine",
    custom: false,
    skill: "medicine",
  },
  menace: {
    key: "menace",
    label: "Skill.menace",
    custom: false,
    skill: "menace",
  },
  performance: {
    key: "performance",
    label: "Skill.performance",
    custom: false,
    skill: "performance",
  },
  preciseMelee: {
    key: "preciseMelee",
    label: "Skill.preciseMelee",
    custom: false,
    skill: "preciseMelee",
    compendium: "weapon-rules",
    journal: "7lkCweZ1AFTg6I94",
  },
  query: {
    key: "query",
    label: "Skill.query",
    custom: false,
    skill: "query",
  },
  scrounge: {
    key: "scrounge",
    label: "Skill.scrounge",
    custom: false,
    skill: "scrounge",
  },
  sleightOfHand: {
    key: "sleightOfHand",
    label: "Skill.sleightOfHand",
    custom: false,
    skill: "sleightOfHand",
  },
  stealth: {
    key: "stealth",
    label: "Skill.stealth",
    custom: false,
    skill: "stealth",
  },
  thrownMissile: {
    key: "thrownMissile",
    label: "Skill.thrownMissile",
    custom: false,
    skill: "thrownMissile",
    compendium: "weapon-rules",
    journal: "aOkX01lemXNa8sYS",
  },
  tracking: {
    key: "tracking",
    label: "Skill.tracking",
    custom: false,
    skill: "tracking",
  },
  traps: {
    key: "traps",
    label: "Skill.traps",
    custom: false,
    skill: "traps",
  },
  unarmedMelee: {
    key: "unarmedMelee",
    label: "Skill.unarmedMelee",
    custom: false,
    skill: "unarmedMelee",
    compendium: "weapon-rules",
    journal: "kzHQncqDG0RSsedf",
  },
};

export const MagicRules: Record<string, EquipmentRule> = {
  bane: {
    key: "bane",
    label: "EquipmentRules.bane",
    custom: false,
    compendium: "magic-rules",
    journal: "UnGgDGz3VacCQckd",
  },
  combatMastery: {
    key: "combatMastery",
    label: "EquipmentRules.combatMastery",
    custom: false,
    compendium: "magic-rules",
    journal: "fc4PsOftXeVngmIx",
  },
  defenseHack: {
    key: "defenseHack",
    label: "EquipmentRules.defenseHack",
    custom: false,
    compendium: "magic-rules",
    journal: "XuvTz3fXilajJVWx",
  },
  downtimeBoost: {
    key: "downtimeBoost",
    label: "EquipmentRules.downtimeBoost",
    custom: false,
    compendium: "magic-rules",
    journal: "60mzQvOmcMqJEsRe",
  },
  elementalAttack: {
    key: "elementalAttack",
    label: "EquipmentRules.elementalAttack",
    custom: false,
    compendium: "magic-rules",
    journal: "GvkYt2w4KMJBTsXv",
  },
  elementalDefense: {
    key: "elementalDefense",
    label: "EquipmentRules.elementalDefense",
    custom: false,
    compendium: "magic-rules",
    journal: "4PiKySt3yEascpBS",
  },
  magicCell: {
    key: "magicCell",
    label: "EquipmentRules.magicCell",
    custom: false,
    compendium: "magic-rules",
    journal: "FWt6c9pS1GC0W18U",
  },
  magicDR: {
    key: "magicDR",
    label: "EquipmentRules.magicDR",
    custom: false,
    compendium: "magic-rules",
    journal: "8CAes5I0AsBH5YmI",
  },
  magicMount: {
    key: "magicMount",
    label: "EquipmentRules.magicMount",
    custom: false,
    compendium: "magic-rules",
    journal: "n3JNTdqdLhk5zOJy",
  },
  magicUpgrade: {
    key: "magicUpgrade",
    label: "EquipmentRules.magicUpgrade",
    custom: false,
    compendium: "magic-rules",
    journal: "8CZTvP8Hs8jur75z",
  },
  masterErWork: {
    key: "masterErWork",
    label: "EquipmentRules.masterErWork",
    custom: false,
    compendium: "magic-rules",
    journal: "Dse43AVrEkQ5JDf1",
  },
  moreHP: {
    key: "moreHP",
    label: "EquipmentRules.moreHP",
    custom: false,
    compendium: "magic-rules",
    journal: "LcwEv0Zo3pvF2aLy",
  },
  moreMP: {
    key: "moreMP",
    label: "EquipmentRules.moreMP",
    custom: false,
    compendium: "magic-rules",
    journal: "MHbFie1k3jdR15G4",
  },
  piercing: {
    key: "piercing",
    label: "EquipmentRules.piercing",
    custom: false,
    compendium: "magic-rules",
    journal: "hBJ1e3NNn5bGKO8q",
  },
  poisonImmunity: {
    key: "poisonImmunity",
    label: "EquipmentRules.poisonImmunity",
    custom: false,
    compendium: "magic-rules",
    journal: "C8ylF1Suzh1C4hSf",
  },
  quietCast: {
    key: "quietCast",
    label: "EquipmentRules.quietCast",
    custom: false,
    compendium: "magic-rules",
    journal: "eaAmhIGZXCZOHDxQ",
  },
  refiller: {
    key: "refiller",
    label: "EquipmentRules.refiller",
    custom: false,
    compendium: "magic-rules",
    journal: "J9KzItOy9EgqL7hu",
  },
  reroller: {
    key: "reroller",
    label: "EquipmentRules.reroller",
    custom: false,
    compendium: "magic-rules",
    journal: "Ndtz1SziVUa4zMlr",
  },
  returner: {
    key: "returner",
    label: "EquipmentRules.returner",
    custom: false,
    compendium: "magic-rules",
    journal: "Fnd6BNS9IuKRVLAf",
  },
  skillSwitch: {
    key: "skillSwitch",
    label: "EquipmentRules.skillSwitch",
    custom: false,
    compendium: "magic-rules",
    journal: "7VTYPTHobYRJTkSj",
  },
  spellAccess: {
    key: "spellAccess",
    label: "EquipmentRules.spellAccess",
    custom: false,
    compendium: "magic-rules",
    journal: "8XIVK7EMs5VszvDc",
  },
  spellBoost: {
    key: "spellBoost",
    label: "EquipmentRules.spellBoost",
    custom: false,
    compendium: "magic-rules",
    journal: "QmJiOXm2wXa5bv5p",
  },
  spellImmunity: {
    key: "spellImmunity",
    label: "EquipmentRules.spellImmunity",
    custom: false,
    compendium: "magic-rules",
    journal: "zvUFuketzrWmbblg",
  },
  talentAccess: {
    key: "talentAccess",
    label: "EquipmentRules.talentAccess",
    custom: false,
    compendium: "magic-rules",
    journal: "13k2JoYMaVRffS1f",
  },
  uplifting: {
    key: "uplifting",
    label: "EquipmentRules.uplifting",
    custom: false,
    compendium: "magic-rules",
    journal: "7BrVg692wbd1masX",
  },
};

export const EquipmentRules: Record<string, EquipmentRule> = {
  ...OutfitRules,
  ...WeaponRules,
  ...MagicRules,
  ...SkillRules,
};
